services:
  - type: web
    name: gita-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
    domains:
      - api.vijaygita.com
